### ISSUE TITLE
`markdown-pdf.styles` option doesn't work with the error: "BAD uri lacks scheme, falling back to file-scheme."

### ISSUE THREAD

**Issue by mysticatea** [yzane/vscode-markdown-pdf#134]
`markdown-pdf.styles` option doesn't work with the following error.
I guess that the fallback breaks your logic because maybe the condition of [extension.js#L727](https://github.com/yzane/vscode-markdown-pdf/blob/b1e5f5bc18c16d6ac40583ae7897c6e81b075723/extension.js#L727) is `true` anyway even if the `markdown-pdf.styles` option was relative.

```
Trace: BAD uri lacks scheme, falling back to file-scheme.
	at c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:120:484
	at new f (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:120:557)
	at new p (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:122:808)
	at Function.parse (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:122:157)
	at fixHref (C:\Users\t-nagashima.AD\.vscode\extensions\yzane.markdown-pdf-1.2.0\extension.js:716:32)
	at readStyles (C:\Users\t-nagashima.AD\.vscode\extensions\yzane.markdown-pdf-1.2.0\extension.js:691:20)
	at makeHtml (C:\Users\t-nagashima.AD\.vscode\extensions\yzane.markdown-pdf-1.2.0\extension.js:299:14)
	at MarkdownPdf (C:\Users\t-nagashima.AD\.vscode\extensions\yzane.markdown-pdf-1.2.0\extension.js:94:22)
	at C:\Users\t-nagashima.AD\.vscode\extensions\yzane.markdown-pdf-1.2.0\extension.js:14:81
	at d._executeContributedCommand (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:492:463)
	at d.$executeContributedCommand (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:492:838)
	at d._doInvokeHandler (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:637:1006)
	at d._invokeHandler (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:637:698)
	at d._receiveRequest (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:636:346)
	at d._receiveOneMessage (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:635:167)
	at define.constructor._protocol.onMessage.e (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:633:432)
	at u.fire (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
	at e (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:43:554)
	at u.fire (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
	at a (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:685)
	at e (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:731)
	at u.fire (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
	at y._receiveMessage (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:184:545)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:860)
	at u.fire (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
	at f.acceptChunk (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:445)
	at define.constructor._register._socket.onData.e (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:177:781)
	at Socket.t (c:\Users\t-nagashima.AD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:186:22)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

**Comment by bryceschober** [comment]
@mysticatea @yzane Could this be why I can't figure out any way to get markdown-pdf to use my styles from my workspace? I feel like I've tried every possible combination of paths in `markdown.styles` and `markdown-pdf.styles` combined with every combination of `markdown-pdf.stylesRelativePathFile` and `markdown-pdf.includeDefaultStyles` settings in my workspace file, and never been able to get my `docs/test_file.md` to export using any one of my `docs/markdown.css`, `docs/markdown-pdf.css`, `docs/markdown-custom.css`, or `docs/markdown-pdf-custom.css`.
